# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

domain: luisgongod.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://luisgongod.github.io  # the base hostname and protocol for your site, e.g. http://example.com
# baseurl: /REPOSITORY-NAME/      # place folder name if the site is served in a subfolder

title: Luis Gonzalez
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal Blog of notes, projects, bio and what.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: LuisGonGod
github_username:  luisgongod

github: [metadata]

# show_downloads: [False]
# google_analytics: [Your Google Analytics tracking ID]
# Build settings
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/slate@v0.2.0
# remote_theme: pages-themes/modernist@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/leap-day@v0.2.0


theme: minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme # add this line to the plugins list if you already have one


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
